### ISSUE TITLE
Cannot get response

### ISSUE THREAD

**Issue by brainplusplus** [stackblogger/bitnet.js#1]
![photo_2024-10-21_13-39-17](https://github.com/user-attachments/assets/93cc8676-4b98-4f25-8c6d-2c80a0010525)

why i cant running, no response at all

**Comment by stackblogger** [comment]
Raised a PR to fix this error: https://github.com/stackblogger/bitnet.js/pull/2

**Comment by stackblogger** [comment]
@brainplusplus The issue has been resolved.


![image](https://github.com/user-attachments/assets/a74a4d5c-5fd8-4333-a8d9-5bca4ad8abc1)
